--------------------------------------------------------
--  파일이 생성됨 - 금요일-5월-16-2025   
--------------------------------------------------------
REM INSERTING into HR.BOOKHUB_CATEGORIES
SET DEFINE OFF;
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (55890,'건강/취미/레저',null);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (53518,'질병치료와 예방',55890);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (53521,'건강정보',55890);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (53532,'공예',55890);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (53522,'걷기/육상스포츠',55890);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (170,'경제경영',null);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (3057,'경제학/경제일반',170);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (2028,'기업/경영자 스토리',170);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (261,'마케팅/세일즈',170);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (2172,'기업 경영',170);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (172,'재테크/투자',170);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (76001,'고등학교참고서',null);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (77441,'EBS 고등',76001);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (77023,'수능모의고사/기출',76001);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (77027,'고등영어전문교재',76001);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (77021,'고등-문제집',76001);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (77022,'수능대비',76001);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (987,'과학',null);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (51038,'공학',987);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (51005,'과학의 이해',987);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (51045,'농업',987);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (51022,'동물과 식물',987);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (51015,'생명과학',987);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (351,'컴퓨터/모바일',null);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (479,'활용능력',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (2630,'그래픽/멀티미디어',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (55977,'모바일 프로그래밍',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (55055,'스마트폰/태블릿/SNS',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (2599,'오피스(엑셀/파워포인트)',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (2719,'컴퓨터 공학',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (6348,'웹디자인/홈페이지',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (7396,'프로그래밍 개발/방법론',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (437,'프로그래밍 언어',351);
Insert into HR.BOOKHUB_CATEGORIES (CATEGORY_NO,CATEGORY_NAME,CATEGORY_PARENTS_NO) values (2349,'e비즈니스/창업',351);
commit;
