--------------------테이블 생성-----------------------

-- 1. 카테고리 테이블
CREATE TABLE "BOOKHUB_CATEGORIES" (
   "CATEGORY_NO"   NUMBER(7)      NOT NULL,
   "CATEGORY_NAME"   VARCHAR2(100)      NOT NULL,
   "CATEGORY_PARENTS_NO"   NUMBER(7)      NULL
);

-- 2. 도서관 테이블
CREATE TABLE "BOOKHUB_LIBRARIES" (
   "LIB_NO"   NUMBER(6)      NOT NULL,
   "LIB_NAME"   VARCHAR2(100)      NOT NULL,
   "LIB_LOCATION"   VARCHAR2(255)      NOT NULL,
   "LIB_LONGITUDE"   VARCHAR2(50)      NOT NULL,
   "LIB_LATITUDE"   VARCHAR2(50)      NOT NULL,
   "LIB_TEL"   VARCHAR(100)      NOT NULL,
   "LIB_IMG_PATH"   VARCHAR2(500)      NOT NULL,
   "LIB_BUSINESS_HOURS"   VARCHAR2(255)      NOT NULL
);

-- 3. 게시물 테이블 
CREATE TABLE "BOOKHUB_POSTS" (
	"POST_NO"	NUMBER(6)		NOT NULL,
	"POST_TITLE"	VARCHAR2(255)		NOT NULL,
	"POST_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"POST_VIEW_CNT"	NUMBER(6)	DEFAULT 0	NULL,
	"POST_CREATED_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"POST_UPDATED_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"IS_DELETED"	CHAR(1)	DEFAULT 'N'	NULL,
	"IS_PUBLIC"	CHAR(1)	DEFAULT 'Y'	NULL,
	"USER_ID"	VARCHAR2(255)		NOT NULL,
	"BOOK_NO"	NUMBER(6)		NOT NULL,
	"LIB_NO"	NUMBER(6)		NOT NULL,
	"POST_CATE_NO"	NUMBER(6)		NOT NULL
);

-- 4. 리뷰 테이블
CREATE TABLE "BOOKHUB_REVIEWS" (
   "REVIEW_NO"   NUMBER(6)      NOT NULL,
   "REVIEW_CONTENT"   VARCHAR2(2000)      NOT NULL,
   "REVIEW_STAR"   NUMBER(1)      NOT NULL,
   "REVIEW_LIKES"   NUMBER(6)   DEFAULT 0   NULL,
   "REVIEW_TITLE"   VARCHAR2(400)      NOT NULL,
   "REVIEW_CREATED_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "REVIEW_UPDATED_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "IS_DELETED"   CHAR(1)   DEFAULT 'N'   NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "BOOK_NO"   NUMBER(6)      NOT NULL
);

-- 5. 사용자 테이블
CREATE TABLE "BOOKHUB_USERS" (
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "USER_PASSWORD"   CHAR(64)      NOT NULL,
   "USER_NAME"   VARCHAR2(100)      NOT NULL,
   "USER_ZIPCODE"   NUMBER(5)      NOT NULL,
   "USER_ADDRESS"   VARCHAR2(255)      NOT NULL,
   "USER_DETAIL"   VARCHAR2(255)      NOT NULL,
   "USER_PHONE"   VARCHAR2(100)      NOT NULL,
   "USER_BIRTH"   DATE      NOT NULL,
   "USER_CREATED_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "USER_UPDATED_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "IS_DELETED"   CHAR(1)   DEFAULT 'N'   NULL
);

-- 6. 키워드 테이블
CREATE TABLE "BOOKHUB_KEYWORDS" (
   "KEYWORD"   VARCHAR2(50)      NOT NULL,
   "BOOK_NO"   NUMBER(6)      NOT NULL
);

-- 7. 재고 수량 테이블
CREATE TABLE "BOOKHUB_STOCKS" (
   "LIB_NO"   NUMBER(6)      NOT NULL,
   "BOOK_NO"   NUMBER(6)      NOT NULL,
   "BOOK_STOCK"   NUMBER(6)   DEFAULT 5   NULL
);

--8. 대여 및 반납 테이블
CREATE TABLE "BOOKHUB_LOAN_HISTORIES" (
   "LOAN_NO"   NUMBER(6)      NOT NULL,
   "LOAN_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "RETURN_DATE"   DATE      NULL,
   "DUE_DATE"   DATE      NOT NULL,
   "LOAN_STATUS"   CHAR(1)   DEFAULT 'R'   NULL,
   "USER_ID"   VARCHAR2(255)      NOT NULL,
   "LIB_NO"   NUMBER(6)      NOT NULL,
   "BOOK_NO"   NUMBER(6)      NOT NULL
);

--9. 도서 테이블
CREATE TABLE "BOOKHUB_BOOKS" (
   "BOOK_NO"   NUMBER(6)      NOT NULL,
   "BOOK_TITLE"   VARCHAR2(400)      NOT NULL,
   "BOOK_AUTHOR"   VARCHAR2(255)      NOT NULL,
   "BOOK_PUBLISHER"   VARCHAR2(255)      NOT NULL,
   "BOOK_DESCRIPTION"   VARCHAR2(2000)      NULL,
   "BOOK_PUB_DATE"   VARCHAR2(100)      NOT NULL,
   "BOOK_REVIEW_COUNT"   NUMBER(6)   DEFAULT 0   NULL,
   "REVIEW_AVG"   NUMBER(2,1)   DEFAULT 0   NULL,
   "BOOK_COVER_IMAGE_PATH"   VARCHAR2(500)      NOT NULL,
   "BOOK_CREATED_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "BOOK_UPDATED_DATE"   DATE   DEFAULT SYSDATE   NULL,
   "BOOK_ISBN"   VARCHAR2(50)      NOT NULL,
   "CATEGORY_NO"   NUMBER(7)      NOT NULL
);

--10. 주소 테이블
CREATE TABLE "BOOKHUB_ADDRESS" (
	"ADDR_NO"	NUMBER(5)		NOT NULL,
	"ADDR_ZIPCODE"	CHAR(5)		NOT NULL,
	"ADDR_BASIC"	VARCHAR2(255)		NOT NULL,
	"ADDR_DETAIL"	VARCHAR2(255)		NULL,
	"ADDR_GIBON"	CHAR(1)	DEFAULT 'N'	NULL,
	"ADDR_CREATED_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ADDR_NAME"	VARCHAR2(100)		NOT NULL,
	"USER_ID"	VARCHAR2(255)		NOT NULL
);

--11. 찜목록 테이블
CREATE TABLE "BOOKHUB_WISHLIST" (
	"BOOK_NO"	NUMBER(6)		NOT NULL,
	"USER_ID"	VARCHAR2(255)		NOT NULL
);

--12. 문의유형 테이블
CREATE TABLE "BOOKHUB_POST_CATEGORIES" (
	"POST_CATE_NO"	NUMBER(6)		NOT NULL,
	"POST_CATE_NAME"	VARCHAR2(255)		NOT NULL
);
--------------------테이블 생성-----------------------
--------------------PRIMARY KEY 제약조건-----------------------

ALTER TABLE "BOOKHUB_CATEGORIES" ADD CONSTRAINT "PK_BOOKHUB_CATEGORIES" PRIMARY KEY (
   "CATEGORY_NO"
);

ALTER TABLE "BOOKHUB_LIBRARIES" ADD CONSTRAINT "PK_BOOKHUB_LIBRARIES" PRIMARY KEY (
   "LIB_NO"
);

ALTER TABLE "BOOKHUB_POSTS" ADD CONSTRAINT "PK_BOOKHUB_POSTS" PRIMARY KEY (
   "POST_NO"
);

ALTER TABLE "BOOKHUB_REVIEWS" ADD CONSTRAINT "PK_BOOKHUB_REVIEWS" PRIMARY KEY (
   "REVIEW_NO"
);

ALTER TABLE "BOOKHUB_USERS" ADD CONSTRAINT "PK_BOOKHUB_USERS" PRIMARY KEY (
   "USER_ID"
);

ALTER TABLE "BOOKHUB_STOCKS" ADD CONSTRAINT "PK_BOOKHUB_STOCKS" PRIMARY KEY (
   "LIB_NO",
   "BOOK_NO"
);

ALTER TABLE "BOOKHUB_LOAN_HISTORIES" ADD CONSTRAINT "PK_BOOKHUB_LOAN_HISTORIES" PRIMARY KEY (
   "LOAN_NO"
);

ALTER TABLE "BOOKHUB_BOOKS" ADD CONSTRAINT "PK_BOOKHUB_BOOKS" PRIMARY KEY (
   "BOOK_NO"
);

ALTER TABLE "BOOKHUB_ADDRESS" ADD CONSTRAINT "PK_BOOKHUB_ADDRESS" PRIMARY KEY (
	"ADDR_NO"
);

ALTER TABLE "BOOKHUB_WISHLIST" ADD CONSTRAINT "PK_BOOKHUB_WISHLIST" PRIMARY KEY (
	"BOOK_NO",
	"USER_ID"
);

ALTER TABLE "BOOKHUB_POST_CATEGORIES" ADD CONSTRAINT "PK_BOOKHUB_POST_CATEGORIES" PRIMARY KEY (
	"POST_CATE_NO"
);
--------------------PRIMARY KEY 제약조건-----------------------
------------------------FOREIGN KEY 제약조건-----------------------

--BOOKHUB_CATEGORIES

ALTER TABLE "BOOKHUB_CATEGORIES" ADD CONSTRAINT "FK_BOOKHUB_CATEGORIES_TO_BOOKHUB_CATEGORIES_1" FOREIGN KEY (
   "CATEGORY_PARENTS_NO"
)
REFERENCES "BOOKHUB_CATEGORIES" (
   "CATEGORY_NO"
);

--BOOKHUB_POSTS

ALTER TABLE "BOOKHUB_POSTS" ADD CONSTRAINT "FK_BOOKHUB_USERS_TO_BOOKHUB_POSTS_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "BOOKHUB_USERS" (
   "USER_ID"
);

ALTER TABLE "BOOKHUB_POSTS" ADD CONSTRAINT "FK_BOOKHUB_POST_CATEGORIES_TO_BOOKHUB_POSTS_1" FOREIGN KEY (
	"POST_CATE_NO"
)
REFERENCES "BOOKHUB_POST_CATEGORIES" (
	"POST_CATE_NO"
);

ALTER TABLE "BOOKHUB_POSTS" ADD CONSTRAINT "FK_BOOKHUB_LIBRARIES_TO_BOOKHUB_POSTS_1" FOREIGN KEY (
	"LIB_NO"
)
REFERENCES "BOOKHUB_LIBRARIES" (
	"LIB_NO"
);

ALTER TABLE "BOOKHUB_POSTS" ADD CONSTRAINT "FK_BOOKHUB_BOOKS_TO_BOOKHUB_POSTS_1" FOREIGN KEY (
	"BOOK_NO"
)
REFERENCES "BOOKHUB_BOOKS" (
	"BOOK_NO"
);

--BOOKHUB_REVIEWS

ALTER TABLE "BOOKHUB_REVIEWS" ADD CONSTRAINT "FK_BOOKHUB_USERS_TO_BOOKHUB_REVIEWS_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "BOOKHUB_USERS" (
   "USER_ID"
);

ALTER TABLE "BOOKHUB_REVIEWS" ADD CONSTRAINT "FK_BOOKHUB_BOOKS_TO_BOOKHUB_REVIEWS_1" FOREIGN KEY (
   "BOOK_NO"
)
REFERENCES "BOOKHUB_BOOKS" (
   "BOOK_NO"
);

--BOOKHUB_KEYWORDS

ALTER TABLE "BOOKHUB_KEYWORDS" ADD CONSTRAINT "FK_BOOKHUB_BOOKS_TO_BOOKHUB_KEYWORDS_1" FOREIGN KEY (
   "BOOK_NO"
)
REFERENCES "BOOKHUB_BOOKS" (
   "BOOK_NO"
);

--BOOKHUB_STOCKS

ALTER TABLE "BOOKHUB_STOCKS" ADD CONSTRAINT "FK_BOOKHUB_LIBRARIES_TO_BOOKHUB_STOCKS_1" FOREIGN KEY (
   "LIB_NO"
)
REFERENCES "BOOKHUB_LIBRARIES" (
   "LIB_NO"
);

ALTER TABLE "BOOKHUB_STOCKS" ADD CONSTRAINT "FK_BOOKHUB_BOOKS_TO_BOOKHUB_STOCKS_1" FOREIGN KEY (
   "BOOK_NO"
)
REFERENCES "BOOKHUB_BOOKS" (
   "BOOK_NO"
);

--BOOKHUB_LOAN_HISTORIES

ALTER TABLE "BOOKHUB_LOAN_HISTORIES" ADD CONSTRAINT "FK_BOOKHUB_USERS_TO_BOOKHUB_LOAN_HISTORIES_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "BOOKHUB_USERS" (
   "USER_ID"
);

ALTER TABLE "BOOKHUB_LOAN_HISTORIES" ADD CONSTRAINT "FK_BOOKHUB_LIBRARIES_TO_BOOKHUB_LOAN_HISTORIES_1" FOREIGN KEY (
   "LIB_NO"
)
REFERENCES "BOOKHUB_LIBRARIES" (
   "LIB_NO"
);

ALTER TABLE "BOOKHUB_LOAN_HISTORIES" ADD CONSTRAINT "FK_BOOKHUB_BOOKS_TO_BOOKHUB_LOAN_HISTORIES_1" FOREIGN KEY (
   "BOOK_NO"
)
REFERENCES "BOOKHUB_BOOKS" (
   "BOOK_NO"
);

--BOOKHUB_BOOKS

ALTER TABLE "BOOKHUB_BOOKS" ADD CONSTRAINT "FK_BOOKHUB_CATEGORIES_TO_BOOKHUB_BOOKS_1" FOREIGN KEY (
   "CATEGORY_NO"
)
REFERENCES "BOOKHUB_CATEGORIES" (
   "CATEGORY_NO"
);

--BOOKHUB_ADDRESS

ALTER TABLE "BOOKHUB_ADDRESS" ADD CONSTRAINT "FK_BOOKHUB_USERS_TO_BOOKHUB_ADDRESS_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "BOOKHUB_USERS" (
	"USER_ID"
);

--BOOKHUB_WISHLIST

ALTER TABLE "BOOKHUB_WISHLIST" ADD CONSTRAINT "FK_BOOKHUB_BOOKS_TO_BOOKHUB_WISHLIST_1" FOREIGN KEY (
	"BOOK_NO"
)
REFERENCES "BOOKHUB_BOOKS" (
	"BOOK_NO"
);

ALTER TABLE "BOOKHUB_WISHLIST" ADD CONSTRAINT "FK_BOOKHUB_USERS_TO_BOOKHUB_WISHLIST_1" FOREIGN KEY (
	"USER_ID"
)
REFERENCES "BOOKHUB_USERS" (
	"USER_ID"
);

------------------------FOREIGN KEY 제약조건-----------------------
-------------------------CHECK 제약조건 설정------------------------------
ALTER TABLE BOOKHUB_USERS
ADD CONSTRAINT CHK_USERS_ISDELETED CHECK (IS_DELETED IN ('Y', 'N'));

ALTER TABLE BOOKHUB_POSTS
ADD CONSTRAINT CHK_POSTS_ISDELETED CHECK (IS_DELETED IN ('Y', 'N'));

ALTER TABLE BOOKHUB_POSTS 
ADD CONSTRAINT CHK_POSTS_ISPUBLIC CHECK (IS_PUBLIC IN ('Y', 'N'));

ALTER TABLE BOOKHUB_REVIEWS
ADD CONSTRAINT CHK_REVIEWS_ISDELETED CHECK (IS_DELETED IN ('Y', 'N'));

ALTER TABLE BOOKHUB_LOAN_HISTORIES
ADD CONSTRAINT CHK_LOAN_STATUS CHECK (LOAN_STATUS IN ('L', 'R', 'D','P'));


-------------------------CHECK 제약조건 설정------------------------------
-------------------------시퀀스 설정------------------------------
-- 도서관 테이블 시퀀스 
CREATE SEQUENCE BOOKHUB_LIBRARIES_LIB_NO_SEQ START WITH 1;

-- 도서 테이블 시퀀스 
CREATE SEQUENCE BOOKHUB_BOOKS_BOOK_NO_SEQ START WITH 1;

-- 도서 대여 및 반납 시퀀스 
CREATE SEQUENCE BOOKHUB_LOAN_HISTORIES_LOAN_NO_SEQ START WITH 1;

-- 게시물 번호 시퀀스 
CREATE SEQUENCE BOOKHUB_POSTS_POST_NO_SEQ START WITH 1;

-- 리뷰 테이블 시퀀스
CREATE SEQUENCE BOOKHUB_REVIEWS_REVIEW_NO_SEQ START WITH 1;

-- 카테고리 테이블 시퀀스
CREATE SEQUENCE BOOKHUB_CATEGORIES_CATEGORY_NO_SEQ START WITH 1;

-- 주소 테이블 시퀀스
CREATE SEQUENCE BOOKHUB_ADDRESS_ADDR_NO_SEQ START WITH 1;

-- 게시물 문의 유형 테이블 시퀀스
CREATE SEQUENCE BOOKHUB_POST_CATEGORIES_POST_CATE_NO_SEQ START WITH 1;
------------------------시퀀스 설정------------------------------