REM INSERTING into HR.BOOKHUB_POST_REPLIES
SET DEFINE OFF;
Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

Insert into HR.BOOKHUB_POST_REPLIES 
(REPLY_NO,PARENT_NO,REPLY_CONTENT,REPLY_CREATED_DATE,REPLY_UPDATED_DATE,IS_DELETED,USER_ID,POST_NO) 
values 
(BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,null,'댓글내용' || BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'Y','user' ||BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval|| '@gmail.com',BOOKHUB_POST_REPLIES_REPLY_NO_SEQ.nextval);

