

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',10,null,1);

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',11,null,1);

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',12,null,1);



Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',null,1,2);

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',null,2,2);

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',null,3,2);



Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',null,null,3);

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',null,null,3);

Insert into HR.BOOKHUB_POSTS 
(POST_NO,POST_TITLE,POST_CONTENT,POST_VIEW_CNT,POST_CREATED_DATE,POST_UPDATED_DATE,IS_DELETED,IS_PUBLIC,USER_ID,BOOK_NO,LIB_NO,POST_CATE_NO) 
values 
(BOOKHUB_POSTS_POST_NO_SEQ.nextval,'반갑습니다. ' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,'<p>반갑습니다.&nbsp;</p>' || BOOKHUB_POSTS_POST_NO_SEQ.nextval,11,to_date('25/05/15','RR/MM/DD'),to_date('25/05/15','RR/MM/DD'),'N','N','user' ||BOOKHUB_POSTS_POST_NO_SEQ.nextval|| '@gmail.com',null,null,3);